---
name: publish

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'

    - name: poetry set version
      run: poetry version ${{ github.ref_name }}

    - name: poetry installation
      run: poetry install

    - name: Poetry Build & Publish
      run: |
        poetry build
        poetry publish
